version: '3.8'

services:
  cclemon-health:
    build: src                    # ğŸ”¥ å¾ç•¶å‰è³‡æ–™å¤¾çš„ Dockerfile å»º image
    image: cclemon-health      # âœ… è‡ªå®šç¾© image åç¨±èˆ‡ tag
    container_name: cclemon-health
    ports:
      - "8888:8888"
    networks:
      - cclemon-network

networks:
  cclemon-network:
    external: true
